name             'lamp'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures lamp'
long_description 'Installs/Configures lamp'
version          '0.1.0'
